<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <AssemblyTitle>VAM Package Updater</AssemblyTitle>
    <Product>VAM Package Updater</Product>
    <Company>emptyngton</Company>
    <Copyright>Copyright (c) 2026 emptyngton</Copyright>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\icon.png"/>
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

</Project>
